import streamlit as st
import io
import os

# ── Page config ────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Text Reader & Transcriber",
    page_icon="🎙️",
    layout="centered",
    initial_sidebar_state="collapsed",
)

# ── Tesseract path detection (Windows local runs only) ─────────────────────────
TESSERACT_PATHS = [
    r"C:\Program Files\Tesseract-OCR\tesseract.exe",
    r"C:\Program Files (x86)\Tesseract-OCR\tesseract.exe",
    r"C:\Users\{}\AppData\Local\Programs\Tesseract-OCR\tesseract.exe".format(
        os.environ.get("USERNAME", "")
    ),
]

def find_tesseract():
    for path in TESSERACT_PATHS:
        if os.path.isfile(path):
            return path
    return None

# ── Extraction helpers ──────────────────────────────────────────────────────────

def extract_from_docx(file_bytes: bytes) -> str:
    """Extract all paragraph text from a .docx file."""
    import docx
    doc = docx.Document(io.BytesIO(file_bytes))
    paragraphs = [p.text for p in doc.paragraphs if p.text.strip()]
    return "\n".join(paragraphs)


def extract_from_pdf(file_bytes: bytes) -> str:
    """Extract text from every page of a PDF."""
    import pdfplumber
    text_parts = []
    with pdfplumber.open(io.BytesIO(file_bytes)) as pdf:
        for page in pdf.pages:
            page_text = page.extract_text()
            if page_text:
                text_parts.append(page_text)
    return "\n\n".join(text_parts)


def extract_from_image(file_bytes: bytes, lang: str = "eng") -> str:
    """Run Tesseract OCR on an image and return the recognised text."""
    import pytesseract
    from PIL import Image

    tess_path = find_tesseract()
    if tess_path:
        pytesseract.pytesseract.tesseract_cmd = tess_path
    else:
        st.error(
            "⚠️ Tesseract OCR not found. "
            "Please install it from https://github.com/UB-Mannheim/tesseract/wiki "
            "and restart the app."
        )
        return ""

    image = Image.open(io.BytesIO(file_bytes))
    return pytesseract.image_to_string(image, lang=lang)


# ── Text-to-speech via gTTS ─────────────────────────────────────────────────────

# gTTS language codes mapped to our OCR language codes for convenience
GTTS_LANG_MAP = {
    "eng": "en",
    "spa": "es",
    "fra": "fr",
    "deu": "de",
    "ita": "it",
    "por": "pt",
    "chi_sim": "zh-CN",
    "jpn": "ja",
}

def generate_audio(text: str, lang_code: str = "en", slow: bool = False) -> bytes:
    """
    Convert text to speech using gTTS and return MP3 bytes.
    gTTS calls Google's TTS service — requires internet but works on
    Streamlit Cloud and every mobile browser via st.audio().
    """
    from gtts import gTTS

    # gTTS can struggle with very long texts in one shot; chunk at ~2 000 chars
    CHUNK_SIZE = 2000
    if len(text) <= CHUNK_SIZE:
        tts = gTTS(text=text, lang=lang_code, slow=slow)
        buf = io.BytesIO()
        tts.write_to_fp(buf)
        return buf.getvalue()

    # For longer texts, generate each chunk and concatenate the raw MP3 bytes
    chunks = [text[i: i + CHUNK_SIZE] for i in range(0, len(text), CHUNK_SIZE)]
    audio_parts = []
    for chunk in chunks:
        tts = gTTS(text=chunk, lang=lang_code, slow=slow)
        buf = io.BytesIO()
        tts.write_to_fp(buf)
        audio_parts.append(buf.getvalue())
    return b"".join(audio_parts)


# ── Sidebar ─────────────────────────────────────────────────────────────────────
with st.sidebar:
    st.title("🎙️ Text Reader")
    st.markdown(
        """
        **How to use:**
        1. Pick an input method (tabs below)
        2. Paste text or upload a file
        3. Click **Extract Text**
        4. Click **🔊 Generate Audio** to create the audio
        5. Press play on the audio player
        """
    )
    st.divider()
    st.subheader("⚙️ Settings")
    slow_mode = st.checkbox("🐢 Slow reading speed", value=False)
    ocr_lang  = st.selectbox(
        "OCR language (images)",
        options=["eng", "spa", "fra", "deu", "ita", "por", "chi_sim", "jpn"],
        format_func=lambda x: {
            "eng": "English", "spa": "Spanish", "fra": "French",
            "deu": "German",  "ita": "Italian", "por": "Portuguese",
            "chi_sim": "Chinese (Simplified)", "jpn": "Japanese",
        }.get(x, x),
    )
    st.divider()
    st.caption("Audio is generated by Google TTS — works on all devices including mobile.")


# ── Main area ───────────────────────────────────────────────────────────────────
st.title("🎙️ Text Reader & Transcriber")
st.caption("Paste text, upload a Word doc, PDF, or image — then have it read back to you.")

# ── Input tabs ──────────────────────────────────────────────────────────────────
tab_paste, tab_word, tab_pdf, tab_image = st.tabs(
    ["📋 Paste Text", "📄 Word Doc", "📑 PDF", "🖼️ Image / Photo"]
)

with tab_paste:
    st.subheader("Paste your text")
    st.caption("Copy from Google Docs, Word, email, websites, or anywhere else.")
    pasted = st.text_area(
        "Paste text here",
        height=250,
        placeholder="Paste any text here…",
        label_visibility="collapsed",
    )
    if st.button("Use This Text", key="use_paste", type="primary"):
        if pasted.strip():
            st.session_state["text"] = pasted.strip()
            st.session_state.pop("audio", None)   # clear old audio
            st.success(f"✅ {len(pasted.split())} words loaded.")
        else:
            st.warning("Nothing to use — text area is empty.")

with tab_word:
    st.subheader("Upload a Word document (.docx)")
    docx_file = st.file_uploader("Choose a .docx file", type=["docx"], key="docx_up")
    if docx_file and st.button("Extract Text from Word Doc", key="ext_docx", type="primary"):
        with st.spinner("Reading document…"):
            try:
                result = extract_from_docx(docx_file.read())
                st.session_state["text"] = result
                st.session_state.pop("audio", None)
                st.success(f"✅ {len(result.split())} words extracted.")
            except Exception as e:
                st.error(f"Could not read file: {e}")

with tab_pdf:
    st.subheader("Upload a PDF")
    pdf_file = st.file_uploader("Choose a PDF file", type=["pdf"], key="pdf_up")
    if pdf_file and st.button("Extract Text from PDF", key="ext_pdf", type="primary"):
        with st.spinner("Reading PDF…"):
            try:
                result = extract_from_pdf(pdf_file.read())
                if not result.strip():
                    st.warning(
                        "No text found — this PDF may be image-based (scanned). "
                        "Try the Image tab instead."
                    )
                else:
                    st.session_state["text"] = result
                    st.session_state.pop("audio", None)
                    st.success(f"✅ {len(result.split())} words extracted.")
            except Exception as e:
                st.error(f"Could not read PDF: {e}")

with tab_image:
    st.subheader("Upload an image or photo")
    st.caption("Works with photos of documents, screenshots, printed text, signs, etc.")
    img_file = st.file_uploader(
        "Choose an image", type=["png", "jpg", "jpeg", "bmp", "tiff"], key="img_up"
    )
    if img_file:
        st.image(img_file, caption="Uploaded image", use_column_width=True)
    if img_file and st.button("Extract Text via OCR", key="ext_img", type="primary"):
        with st.spinner("Running OCR — this may take a few seconds…"):
            try:
                result = extract_from_image(img_file.read(), lang=ocr_lang)
                if not result.strip():
                    st.warning("No text detected in this image.")
                else:
                    st.session_state["text"] = result
                    st.session_state.pop("audio", None)
                    st.success(f"✅ {len(result.split())} words detected.")
            except Exception as e:
                st.error(f"OCR failed: {e}")


# ── Output area ─────────────────────────────────────────────────────────────────
st.divider()
st.subheader("📝 Extracted / Transcribed Text")

current_text = st.session_state.get("text", "")

if current_text:
    # Editable display — user can tweak before generating audio
    edited_text = st.text_area(
        "Text (editable — make changes before generating audio)",
        value=current_text,
        height=300,
        label_visibility="collapsed",
        key="text_display",
    )

    col1, col2, col3 = st.columns([2, 2, 1])
    with col1:
        word_count = len(edited_text.split())
        char_count = len(edited_text)
        st.caption(f"**{word_count:,} words · {char_count:,} characters**")
    with col3:
        if st.button("🗑️ Clear", key="clear_text"):
            st.session_state.pop("text", None)
            st.session_state.pop("audio", None)
            st.rerun()

    # Copy-to-clipboard button
    safe_text = edited_text.replace("\\", "\\\\").replace("`", "\\`").replace("$", "\\$")
    copy_js = f"""
    <script>
      function copyText() {{
        navigator.clipboard.writeText(`{safe_text}`)
          .then(() => document.getElementById('copy-msg').textContent = '✅ Copied!')
          .catch(() => document.getElementById('copy-msg').textContent = '❌ Copy failed');
        setTimeout(() => document.getElementById('copy-msg').textContent = '', 2000);
      }}
    </script>
    <button onclick="copyText()"
      style="padding:8px 16px; font-size:14px; border-radius:6px;
             background:#1E88E5; color:white; border:none; cursor:pointer; margin-right:8px;">
      📋 Copy to Clipboard
    </button>
    <span id="copy-msg" style="font-size:13px; color:green;"></span>
    """
    st.components.v1.html(copy_js, height=50)

    # ── Text-to-speech ──────────────────────────────────────────────────────────
    st.subheader("🔊 Read Aloud")

    # Warn for very long texts (gTTS may be slow)
    if word_count > 1500:
        st.warning(
            f"⏳ This text is {word_count:,} words — audio generation may take "
            "20–30 seconds. Consider trimming it or reading in sections."
        )

    if st.button("🔊 Generate Audio", type="primary", key="gen_audio"):
        gtts_lang = GTTS_LANG_MAP.get(ocr_lang, "en")
        with st.spinner("Generating audio — please wait…"):
            try:
                audio_bytes = generate_audio(edited_text, lang_code=gtts_lang, slow=slow_mode)
                st.session_state["audio"] = audio_bytes
            except Exception as e:
                st.error(f"Audio generation failed: {e}")

    # Show the player if audio has been generated
    if "audio" in st.session_state:
        st.audio(st.session_state["audio"], format="audio/mp3")
        st.caption("▲ Use the player above to play, pause, or seek. Works on all devices.")

        # Download button so users can save the audio file
        st.download_button(
            label="⬇️ Download MP3",
            data=st.session_state["audio"],
            file_name="transcription.mp3",
            mime="audio/mpeg",
        )

else:
    st.info("👆 Choose an input method above, then click the Extract button to get started.")
